### ISSUE TITLE
Request: add GitHub's "alert" markdown syntax

### ISSUE THREAD

**Issue by mdrxy** [techfolios/template#16]
[Experimenting with GitHub's "alert" markdown syntax](https://blog.jakelee.co.uk/github-alert-experiments/)

**Comment by philipmjohnson** [comment]
Techfolios is based on Jekyll, and so there's no easy way to hook into GitHub's markdown processor.

I think the best way to do this is to define an includes file like alert.html and use that. Here is an example:

https://mcraiha.github.io/jekyll/alert/liquid/markdown/template/2018/07/22/jekyll-alerts-aka-colored-boxes.html

**Comment by mdrxy** [comment]
Cheers, that [worked wonderfully](https://github.com/mdrxy/mdrxy.com/commit/403f8727ce916b093e774bbf8165563345956a1d):

<img width="1340" alt="Screenshot 2024-07-19 at 03 04 46" src="https://github.com/user-attachments/assets/5499ff84-71ea-4981-baa9-c444aea94419">
<img width="1336" alt="Screenshot 2024-07-19 at 03 04 57" src="https://github.com/user-attachments/assets/92e09add-4bfd-448d-b5cf-1bc5ec1fb76f">

[Source](https://mdrxy.com/essays/abe-packages.html)
