### ISSUE TITLE
Headshot from the repo

### ISSUE THREAD

**Issue by mekiisupertramp** [techfolios/template#17]
Hello, I'd like to know if there is any possibility to use a headshot from /img folder inside the repo? I pushed a picture in this folder and tried to make bio.json point to it but it didn't work

**Comment by philipmjohnson** [comment]
Yes. The approach is to specify the headshot as a URL, not as a relative file path. 

To do this, open your portfolio repo in a browser, then navigate to the headshot file in your img subdirectory. Then right-click on the image and select "Open image in new tab".  This will display the image in a new tab, but more importantly, the address bar will now contain the URL to the image.  It will look something like this:

```
https://raw.githubusercontent.com/<org>/<repo>/<branch>/<path-to-file>/headshot.png
```

Or maybe it's .jpg, but you get the idea. 

Use that URL in your bio.json and you should be fine.

**Comment by mekiisupertramp** [comment]
Ok, I did it wrong first time. I didn't open the image in a new tab and the URL was something like:

https://github.com/mekiisupertramp/mekiisupertramp.github.io/blob/main/img/profile.png

Now it works. Thanks a lot!
