### ISSUE TITLE
How to add custom icons in profiles?

### ISSUE THREAD

**Issue by shvmsaini** [techfolios/template#6]
![image](https://user-images.githubusercontent.com/29869969/196776000-13bc5700-05e2-4c0e-897e-be39f4d523a2.png)
I want to add an icon  that bootstrap doesn't have, how do I add it?

**Comment by philipmjohnson** [comment]
Here is a post with some suggestions:

https://talk.jekyllrb.com/t/help-creating-icons-emojis/6227
